### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Phonavis** [Zairus/IskalliumReactors#7]
Iskallium Reactors 0.3.7
Foolcraft version 1.2.1

Attempted to put a Thermal Expansion infuser next to a power tap, got this - https://pastebin.com/Hadfkxn3

**Comment by WinterGrave** [comment]
Thanks, I'm researching this issue. It seems to occur in thermal expansion due to an output value it's getting from Iskallium Reactors. But I can't see thermal expansion's code so it's taking me time.

**Comment by dxns-hub** [comment]
@WinterGrave I do believe I had an output setting on the side of the power cell attached to the power tap. I've used one on a private server before with no issues but I do believe it was configured as input on the cell at the time.

**Comment by WinterGrave** [comment]
That is the problem indeed. The cell thinks the power tap can receive power when it only sends power. I have to find out why the power tap is telling other tile entities it can receive power when it actually can't. But at the moment I don't have access to do code properly due to pc issues. Once I sort it out I will continue and fix,

**Comment by WinterGrave** [comment]
This was fixed on the latest update
